variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

stages:
  - env
  - build
  - deploy
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch

patch:
  stage: env
  image: docker:stable
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[patch]/
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"
    - IMAGE="${CI_REGISTRY_IMAGE}/patch:${CI_PIPELINE_ID}"
    - docker image build . -f docker/sky-above/inflex/patch.Dockerfile -t "$IMAGE"
    - docker push "$IMAGE"

build-prod:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[prod]/
  script:
    - sed -i.bak "s/git@gitlab.com:/https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com\//" stack.yaml
    - IMAGE="${CI_REGISTRY_IMAGE}/prod:${CI_PIPELINE_ID}"
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"
    - date
    - docker image build . -f docker/sky-above/inflex/prod.Dockerfile -t "$IMAGE"
    - date
    - docker push "$IMAGE"
    - date

kube-update:
  stage: deploy
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[prod]/
  image: ubuntu

  before_script:
    - apt-get update -y && apt-get install git -y
    - git config --global user.email "gitlab@inflex.io"
    - git config --global user.name "GitLab runner"

  script:
  - sed -E "s/\/prod:[0-9a-z]+$/\/prod:$CI_PIPELINE_ID/" kube/inflex-server.yaml -i
  - git add kube/inflex-server.yaml
  - git commit -m "Update kube/inflex-server.yaml to $CI_PIPELINE_ID [kube-apply]"
  - git push "https://gitlab-ci-token:$GITLAB_PUSH_TOKEN@gitlab.com/sky-above/inflex.git" HEAD:$CI_COMMIT_BRANCH

kube-apply:
  stage: deploy
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[kube-apply]/
  before_script:
  - sh .gitlab/setup-ssh.sh
  script:
  - scp -v kube/* rancher@46.101.49.42:kube/
  - ssh -v rancher@46.101.49.42 ./kubectl apply -f kube
