apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflex-server
  labels:
    app: inflex-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inflex-server
  template:
    metadata:
      labels:
        app: inflex-server
    spec:
      containers:
      - name: inflex-server
        # TODO: Change the health token (and in load balancer section)
        # after changing this image to actual inflex.
        # Later, this sha256 will be replaced by "latest" or whatnot and CI can use "set image".
        # TODO: How do I let k8s access gitlab's registry?
        image: chrisdone/lbtest@sha256:f26b21a619545e4d2fdbf1fbe5b07f6dadc426c3275bdea74d849a2fb89d63b8
        env:
          - name: PORT
            value: "80"
          - name: HEALTH_TOKEN
            value: "7QrcEkZmQ9jR57KE5MHH3kMJquGu9G"
          # - name: PROXY_OPTIONAL
          #   value: "true"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
        ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: london-lb15
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "london-lb15"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "ac5300c5-cb18-4699-8bf1-df91d8dd98ba"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "inflex.io"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health?token=7QrcEkZmQ9jR57KE5MHH3kMJquGu9G"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "8"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "6"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
    # service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
spec:
  type: LoadBalancer
  selector:
    app: inflex-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
