resolver: lts-14.20
allow-newer: true
ghc-options:
  purescript: '-j4 -O2'
  psc-package: '-j4 -O2'
  inflex-server: '-j4 -O0'
  inflex-engine: '-j4 -O0'
packages:
- inflex-client
- inflex-server
- inflex-engine
extra-deps:
- happy-1.19.9
- github: purescript/purescript
  commit: ed130c78b708ff55cf4a80b126a1bd3ba5d80eb9
- github: purescript/psc-package
  commit: 24a696131bca63513a84d0a9b691f773c7b37069
- github: chrisdone/purescript-bundle-fast
  commit: c5a75b57cd2aa442bf03edfe5a6702b4df0fc45e
- github: chrisdone/yesod-lucid
  commit: cde88d0736a44163be70044a109798f578151db3
- github: chrisdone/forge
  commit: 064fec0762d934336988551a3473aada3b64f8a0
