apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflex-server
  namespace: ingress-nginx
  labels:
    app: inflex-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inflex-server
  template:
    metadata:
      labels:
        app: inflex-server
    spec:
      volumes:
      - name: config-yml
        secret:
          secretName: inflex-server-config
      - name: uploads-storage
        emptyDir: {}
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: inflex-server
        image: registry.gitlab.com/sky-above/inflex/prod:6cf8d0a7dd0db25f4ce2241b2339c9c5b35301f1
        env:
          - name: PORT
            value: "80"
          - name: CONFIG
            value: "/etc/inflex/config.yml"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-yml
          mountPath: "/etc/inflex/"
          readOnly: true
        - name: uploads-storage
          mountPath: "/data/uploads/"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
          - containerPort: 80
            name: nginx-port
          - containerPort: 9090
            name: metrics-port
---
apiVersion: v1
kind: Service
metadata:
  name: inflex-server
  namespace: ingress-nginx
spec:
  ports:
  - port: 80
    targetPort: nginx-port
  selector:
    app: inflex-server
