apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflex-server
  labels:
    app: inflex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflex-server
  template:
    metadata:
      labels:
        app: inflex-server
    spec:
      volumes:
      - name: config-yml
        secret:
          secretName: inflex-server-config
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: inflex-server
        image: registry.gitlab.com/sky-above/inflex/prod:239039819
        env:
          - name: PORT
            value: "80"
          - name: CONFIG
            value: "/etc/inflex/config.yml"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-yml
          mountPath: "/etc/inflex/"
          readOnly: true
        readinessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: "/health"
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
          - containerPort: 80
            name: nginx-port
          - containerPort: 9090
            name: metrics-port
---
apiVersion: v1
kind: Service
metadata:
  name: inflex-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: nginx-port
  selector:
    app: inflex-server
