# None of this is of particular interest. It just says "scrape yourself (prometheus), and scrape kubernetes."
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'k8s-pods'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
        - ingress-nginx # My particular namespace. I think this is required.
                        # I don't remember now. TODO: Update on whether this is required.

# Interesting bit:

    selectors:
      - role: pod
        label: "app=inflex-server" # <--- Just that one pod. You could configure others.
                                   #  In my case, I'm only interested in getting metrics for one pod. Not ALL pods.


  # The syntax here is pretty hard to read documentation for; pretty arcane. But it works once you trudge enough.
  relabel_configs:
    # Just to simplify what label we get, it'll be pod_name=mypod-abc123
  - source_labels: ["__meta_kubernetes_pod_name"]
    action: replace
    target_label: "pod_name"

    # This acts as a "keep" filter, keep only the ones where the container port is "metrics-port".
    # That's what lets us ignore the port 80 which does not expose such /metrics.
  - source_labels: ["__meta_kubernetes_pod_container_port_name"]
    action: keep
    regex: metrics-port # This means we only keep targets that are for metrics.
