name:                inflex-server
version:             0.1.0.0
github:              "githubuser/inflex-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- config/*
- js/*.js
- templates/*.lucius
- templates/*.julius
- svg/*.svg

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/inflex-server#readme>

dependencies:
- criterion-measurement
- conduit
- conduit-extra
- path
- byteunits
- mutable-containers
- prometheus
- async
- early
- yesod-core
- profunctors
- contravariant
- rio
- cassava
- deepseq
- formatting
- time-qq
- th-lift
- markdown
- blaze-markup
- githash
- unliftio
- wai-extra
- http-conduit
- yaml
- cookie
- optics
- validation
- persistent-postgresql
- persistent-sqlite
- base >= 4.7 && < 5
- yesod
- warp
- wai-extra
- wai
- network
- http-types
- bytestring
- stm
- vector
- text
- aeson
- unordered-containers
- exceptions
- monad-logger
- containers
- mtl
- yesod-lucid
- lucid
- uuid
- shakespeare
- template-haskell
- th-utilities
- raw-strings-qq
- filepath
- directory
- file-embed
- time
- persistent-template
- email-validate
- forge
- transformers
- resource-pool
- yesod-persistent
- persistent
- inflex-shared
- inflex-lang
- attoparsec
- memory
- base16-bytestring
- th-orphans
- cryptonite
- string-quote
- hashable
- insert-ordered-containers

flags:
 release:
   manual: True
   default: False
 postgresql:
   manual: True
   default: False

library:
  source-dirs: src
  exposed-modules:
    - Inflex.Server.Types
    - Inflex.Backend
    - Inflex.Server.App
    - Inflex.Server.Dispatch
    - Inflex.Server.Csv
    - Inflex.Migrate
    - Inflex.Schema
    - RIO.Warp
  when:
  - condition: flag(release)
    then:
      source-dirs: src/release
    else:
      source-dirs: src/debug
  - condition: flag(postgresql)
    then:
      source-dirs: src/postgresql
    else:
      source-dirs: src/sqlite

executables:
  inflex-server:
    main:                Main.hs
    source-dirs:         app
    when:
    - condition: flag(release)
      then:
        source-dirs: app/release
      else:
        source-dirs: app/debug
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - inflex-server

tests:
  inflex-types:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - inflex-lang
      - inflex-server
      - inflex-shared

benchmarks:
  inflex-server-bench:
    source-dirs: bench
    main: Csv.hs
    dependencies:
      - criterion
      - inflex-lang
      - inflex-server
      - inflex-shared
