name:                inflex-lang
version:             0

dependencies:
- hspec-expectations
- syb
- lexx
- persistent
- insert-ordered-containers
- base >= 4.7 && < 5
- genvalidity
- QuickCheck
- mutable-containers
- unordered-containers
- hashable
- hspec
- validity
- cryptonite
- genvalidity-property
- genvalidity-hspec
- text
- megaparsec
- reparsec
- validation
- mtl
- transformers
- semigroupoids
- monad-validate
- containers
- optics
- optics-core
- template-haskell
- bytestring
- split
- semigroupoids
- aeson
- memory
- base16-bytestring
- early
- th-orphans
- attoparsec
- rio
- uuid
- parallel
- vector
- deepseq
- th-lift
- flatparse
- byteunits
- sdl2
- persistent-sqlite

ghc-options: -Wall

library:
  source-dirs: src

executables:
  inflex:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -static
    cc-options: -static
    ld-options: -static -pthread
    dependencies: inflex-lang

tests:
  inflex-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inflex-lang

benchmarks:
  inflex-lang-time:
    main: Time.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -threaded
    dependencies:
    - criterion
    - inflex-lang
