name:                inflex-lang
version:             0

dependencies:
- base >= 4.7 && < 5
- genvalidity
- QuickCheck
- hspec
- validity
- cryptonite
- genvalidity-property
- genvalidity-hspec
- text
- megaparsec
- reparsec
- validation
- mtl
- transformers
- semigroupoids
- monad-validate
- containers
- optics
- optics-core
- template-haskell
- bytestring

ghc-options: -Wall

library:
  source-dirs: src

tests:
  inflex-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inflex-lang
    - hint
