name:                inflex-lang
version:             0

dependencies:
- base >= 4.7 && < 5
- genvalidity
- QuickCheck
- mutable-containers
- unordered-containers
- hashable
- hspec
- validity
- cryptonite
- genvalidity-property
- genvalidity-hspec
- text
- megaparsec
- reparsec
- validation
- mtl
- transformers
- semigroupoids
- monad-validate
- containers
- optics
- optics-core
- template-haskell
- bytestring
- split
- semigroupoids
- aeson
- memory
- base16-bytestring
- early
- th-orphans
- attoparsec
- rio
- uuid
- parallel
- vector
- deepseq
- th-lift
- flatparse
- byteunits

ghc-options: -Wall

library:
  source-dirs: src

tests:
  inflex-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inflex-lang
    - hint

benchmarks:
  inflex-lang-time:
    main: Time.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -threaded
    dependencies:
    - criterion
    - inflex-lang
