name:                inflex-shared
version:             0

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- vector
- template-haskell
- async

ghc-options: -Wall

extra-source-files:
- templates/Schema.hs
- templates/Schema.purs
- config/rpc
- config/schema

library:
  source-dirs: src
  exposed-modules: Inflex.Shared.Gen
  other-modules: Inflex.Shared.TH
