name:                inflex-shared
version:             0

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- vector
- inflex-pgmf

ghc-options: -Wall

library:
  source-dirs: src
  exposed-modules: Inflex.Shared.Spec
