name:                inflex-client
version:             0
extra-source-files:
- src/*
dependencies:
- purescript
- base
- template-haskell
- typed-process
- directory
- filepath
library:
  source-dirs: src
