name:                inflex-client
version:             0
extra-source-files:
- src/*
dependencies:
- purescript
- base
- template-haskell
- typed-process
- directory
library:
  source-dirs: src
  exposed-modules:
    Paths_inflex_client
