name:                inflex-client
version:             0

dependencies:
- base >= 4.7 && < 5
- genvalidity
- QuickCheck
- hspec
- validity
- genvalidity-property
- genvalidity-hspec
- text
- mtl
- transformers
- semigroupoids
- containers
- bytestring
- aeson
- typed-process
- directory
- vector

ghc-options: -Wall

# library:
#   source-dirs: src

tests:
  inflex-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
